version: '3.3'

services:
  web:
    build: web
    image: dockerdemos/lab-web
    volumes:
     - "/C:/Users/komako/git/github/k8s-test/web/static/:/static"
    ports:
     - "80:80"

  words:
    build: words
    image: dockerdemos/lab-words
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 16M

  db:
    build: db
    image: dockerdemos/lab-db